/** Icons generated by create-react-icons. Don't edit this file directly. **/
import React from "react";
import PropTypes from "prop-types";

export function Domains(props) {
  const { size, color, ...other } = props;
  return (
    <svg viewBox="0 0 20 18" fill="none" height={size} width={size} {...other}>
      <path
        d="M15 1H5C2.791 1 1 2.791 1 5C1 7.209 2.791 9 5 9H15C17.209 9 19 7.209 19 5C19 2.791 17.209 1 15 1ZM9 5H15H9ZM15 9H5C2.791 9 1 10.791 1 13C1 15.209 2.791 17 5 17H15C17.209 17 19 15.209 19 13C19 10.791 17.209 9 15 9Z"
        stroke={color}
        strokeWidth="1.5"
        strokeLinecap="round"
        strokeLinejoin="round"
      />
    </svg>
  );
}

Domains.defaultProps = {
  color: "currentColor",
  size: 24,
};

Domains.propTypes = {
  color: PropTypes.string,
  size: PropTypes.oneOfType([PropTypes.string, PropTypes.number]),
};
