/** Icons generated by create-react-icons. Don't edit this file directly. **/
import React from "react";
import PropTypes from "prop-types";

export function FileUpload(props) {
  const { size, color, ...other } = props;
  return (
    <svg viewBox="0 0 24 24" fill="none" height={size} width={size} {...other}>
      <path
        d="M18 10V7.828C18 7.298 17.789 6.789 17.414 6.414L14.586 3.586C14.211 3.211 13.702 3 13.172 3H6C4.895 3 4 3.895 4 5V19C4 20.105 4.895 21 6 21H10"
        stroke={color}
        strokeWidth="1.5"
        strokeLinecap="round"
        strokeLinejoin="round"
      />
      <path
        d="M18.295 17.5H14.706M18 8H14C13.448 8 13 7.552 13 7V3L18 8ZM16.5 22C14.015 22 12 19.985 12 17.5C12 15.015 14.015 13 16.5 13C18.986 13 21 15.015 21 17.5C21 19.985 18.986 22 16.5 22ZM16.5 15.705V19.294V15.705Z"
        stroke={color}
        strokeWidth="1.5"
        strokeLinecap="round"
        strokeLinejoin="round"
      />
    </svg>
  );
}

FileUpload.defaultProps = {
  color: "currentColor",
  size: 24,
};

FileUpload.propTypes = {
  color: PropTypes.string,
  size: PropTypes.oneOfType([PropTypes.string, PropTypes.number]),
};
