/** Icons generated by create-react-icons. Don't edit this file directly. **/
import React from "react";
import PropTypes from "prop-types";

export function Home(props) {
  const { size, color, ...other } = props;
  return (
    <svg viewBox="0 0 18 18" fill="none" height={size} width={size} {...other}>
      <path
        d="M1.65244 7.01244L9.00178 1L16.3484 7.01244C16.7609 7.34933 17 7.85511 17 8.38756V15.2222C17 16.2044 16.2044 17 15.2222 17H2.77778C1.79556 17 1 16.2044 1 15.2222V8.38844C1 7.85511 1.23911 7.34933 1.65244 7.01244V7.01244Z"
        stroke={color}
        strokeWidth="1.5"
        strokeLinecap="round"
        strokeLinejoin="round"
      />
    </svg>
  );
}

Home.defaultProps = {
  color: "currentColor",
  size: 24,
};

Home.propTypes = {
  color: PropTypes.string,
  size: PropTypes.oneOfType([PropTypes.string, PropTypes.number]),
};
