/** Icons generated by create-react-icons. Don't edit this file directly. **/
import React from "react";
import PropTypes from "prop-types";

export function ListWithCheck(props) {
  const { size, color, ...other } = props;
  return (
    <svg
      viewBox="0 0 24 24"
      fill="none"
      height={size}
      width={size}
      title="list-with-check-ico"
      {...other}
    >
      <path
        d="M3 18L4.22 19.1L6.688 16.87M3 12L4.22 13.1L6.68 10.87M11 18.5H21M11 12.5H21M3 6L4.22 7.104L6.68 4.874M11 6.5H21"
        stroke={color}
        strokeWidth="1.5"
        strokeLinecap="round"
        strokeLinejoin="round"
      />
    </svg>
  );
}

ListWithCheck.defaultProps = {
  color: "currentColor",
  size: 24,
};

ListWithCheck.propTypes = {
  color: PropTypes.string,
  size: PropTypes.oneOfType([PropTypes.string, PropTypes.number]),
};
