/** Icons generated by create-react-icons. Don't edit this file directly. **/
import React from "react";
import PropTypes from "prop-types";

export function Logout(props) {
  const { size, color, ...other } = props;
  return (
    <svg viewBox="0 0 15 15" fill="none" height={size} width={size} {...other}>
      <path
        d="M0.75 15C0.551088 15 0.360322 14.921 0.21967 14.7803C0.0790178 14.6397 0 14.4489 0 14.25V0.75C0 0.551088 0.0790178 0.360322 0.21967 0.21967C0.360322 0.0790176 0.551088 0 0.75 0H11.25C11.4489 0 11.6397 0.0790176 11.7803 0.21967C11.921 0.360322 12 0.551088 12 0.75V3H10.5V1.5H1.5V13.5H10.5V12H12V14.25C12 14.4489 11.921 14.6397 11.7803 14.7803C11.6397 14.921 11.4489 15 11.25 15H0.75ZM10.5 10.5V8.25H5.25V6.75H10.5V4.5L14.25 7.5L10.5 10.5Z"
        fill={color}
      />
    </svg>
  );
}

Logout.defaultProps = {
  color: "currentColor",
  size: 24,
};

Logout.propTypes = {
  color: PropTypes.string,
  size: PropTypes.oneOfType([PropTypes.string, PropTypes.number]),
};
