/** Icons generated by create-react-icons. Don't edit this file directly. **/
import React from "react";
import PropTypes from "prop-types";

export function Minus(props) {
  const { size, color, ...other } = props;
  return (
    <svg viewBox="0 0 16 2" fill="none" height={size} width={size} {...other}>
      <path
        d="M1 1H15"
        stroke={color}
        strokeWidth="1.5"
        strokeLinecap="round"
        strokeLinejoin="round"
      />
    </svg>
  );
}

Minus.defaultProps = {
  color: "currentColor",
  size: 24,
};

Minus.propTypes = {
  color: PropTypes.string,
  size: PropTypes.oneOfType([PropTypes.string, PropTypes.number]),
};
