/** Icons generated by create-react-icons. Don't edit this file directly. **/
import React from "react";
import PropTypes from "prop-types";

export function RightArrow(props) {
  const { size, color, ...other } = props;
  return (
    <svg viewBox="0 0 17 14" fill="none" height={size} width={size} {...other}>
      <path
        d="M9.98902 13.0121L16 7.0001L9.98902 0.9881M15.992 7.0201L1.00202 7.0201L15.992 7.0201Z"
        stroke={color}
        strokeWidth="1.5"
        strokeLinecap="round"
        strokeLinejoin="round"
      />
    </svg>
  );
}

RightArrow.defaultProps = {
  color: "currentColor",
  size: 24,
};

RightArrow.propTypes = {
  color: PropTypes.string,
  size: PropTypes.oneOfType([PropTypes.string, PropTypes.number]),
};
